mindmap
  root((Formateur))
    Ressent
      Préoccupé par la documentation complète et accessible des séances.
      Besoin d’un outil fiable pour planifier et suivre les activités pédagogiques.
    Dit
      "Je veux que chaque séance soit clairement documentée."
      "Les enseignants et responsable doivent pouvoir accéder au contenu facilement."
    Fait
      Note les objectifs et activités de chaque séance sur vieil outil
      Partage les documents avec le responsable à la fin de chaque cours.
    Besoin
      Un système centralisé pour consigner les objectifs, les modules et de chaque séance.
      Une fonctionnalité pour suivre la progression des cours et partager les informations en temps réel.
      Pouvoir insérer les modules de formation que les étudiants doivent apprendre.
    Contexte
      Dispose déjà d’un outil pour créer le cahier de texte.
      Souhaite enrichir cet outil avec une gestion structurée des modules d’enseignement.
