mindmap
  root((Responsable))
    Ressent
      Difficulté à suivre précisément la progression réelle des cours.
      Manque de visibilité sur l’activité des formateurs.
    Dit
      "Je dois valider les modules enseignés dans chaque séance."
      "Je veux connaître le nombre d’heures effectuées pour chaque module."
      "Je dois suivre la présence et l’activité des formateurs."
    Fait
      Reçoit les documents manuellement à la fin de chaque cours.
      Compile des données dans des feuilles Excel ou des rapports.
    Besoin
      Un tableau de bord
      Accès en temps réel aux informations saisies par les formateurs.
      Système de notification ou de demande de validation après chaque saisie de séance.
    Contexte
      Travaille en coordination avec plusieurs formateurs.
      Dispose d’outils partiels mais non intégrés pour le suivi pédagogique.
