@startuml
left to right direction
skinparam packageStyle rect

actor Teacher as T


package "Notes and Activities Management" {
    usecase "Create Session" as CS
    usecase "Add Activities" as AA
    usecase "Assign Notes" as AN
    usecase "View Reports" as VR

}

T -- CS
T -- AA
T -- AN
T -- VR



@enduml
