@startuml
left to right direction
skinparam packageStyle rectangle

actor Formateur
actor Responsable

rectangle "Cahier de Texte" {
  
  usecase "Choisir un module"
  usecase "Saisir date + heure début + durée (ex : 5h)"
  usecase "Calcul automatique de l’heure de fin"
  usecase "Enregistrer la session (non modifiable)"
  usecase "Afficher les sessions du formateur"
  usecase "Afficher les sessions dans tableau de bord"
  usecase "Valider une session"

 
  Formateur --> "Choisir un module"
  Formateur --> "Saisir date + heure début + durée (ex : 5h)"
  Formateur --> "Calcul automatique de l’heure de fin"
  Formateur --> "Enregistrer la session (non modifiable)"
  Formateur --> "Afficher les sessions du formateur"

  Responsable --> "Afficher les sessions dans tableau de bord"
  Responsable --> "Valider une session"
}
@enduml
