@startuml
left to right direction
skinparam packageStyle rectangle

actor Responsable

rectangle "Sprint 2 - Responsable" {

  usecase "Se connecter"
  usecase "Afficher sessions à valider"
  usecase "Consulter détails session"
  usecase "Valider la session"
  usecase "Voir état de validation"

  Responsable --> "Se connecter"
  Responsable --> "Afficher sessions à valider"
  Responsable --> "Consulter détails session"
  Responsable --> "Valider la session"
  Responsable --> "Voir état de validation"
}
@enduml
