@startuml
left to right direction
skinparam packageStyle rectangle

actor Formateur

rectangle "Sprint 1 - Formateur" {

  usecase "Se connecter"
  usecase "Sélectionner un module"
  usecase "Saisir date, heure début et durée"
  usecase "Calcul automatique heure fin"
  usecase "Enregistrer la session"
  usecase "Voir mes sessions (lecture seule)"

  Formateur --> "Se connecter"
  Formateur --> "Sélectionner un module"
  Formateur --> "Saisir date, heure début et durée"
  Formateur --> "Calcul automatique heure fin"
  Formateur --> "Enregistrer la session"
  Formateur --> "Voir mes sessions (lecture seule)"
}
@enduml
