@startuml
left to right direction
skinparam packageStyle rectangle

actor Formateur

rectangle "Sprint 2 - Formateur" {

  usecase "Se connecter"
  usecase "CRUD Modules"

  Formateur -- "Se connecter"
  Formateur -- "CRUD Modules"

}
@enduml